header:
  user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
base_url: https://www.funda.nl/en
keep_cols:
  sold_data:
    - date_sold
    - ym_sold
    - year_sold
#    - term_days
  selling_data:
    - url
    - house_id
    - city
    - house_type
    - building_type
    - price
    - price_m2
    - room
    - bedroom
    - bathroom
    - living_area
    - energy_label
    - zip
    - address
    - year_built
    - house_age
    # - date_list
    # - ym_list
    # - year_list
    - descrip
    - photo
css_selector:
  url: none
  price: "Asking price"
  address: ""
  descrip: ""
  zip_code: ""
  size: "Plot size"
  year: "Year of construction"
  living_area: "Living area"
  kind_of_house: "Kind of house"
  building_type: "Building type"
  num_of_rooms: "Number of rooms"
  num_of_bathrooms: "Number of bath rooms"
  energy_label: "Energy label"
  insulation: "Insulation"
  heating: "Heating"
  ownership: "Ownership situation"
  parking: "Type of parking facilities"
  city: ""
  neighborhood_name: ""
